name: Build zh_TW manual

on:
  push:
    branches:
      - master

jobs:
  build_dist:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Sphinx and Jieba
      run: |
        python3 -m pip install sphinx jieba
    - name: Clone docs
      run: |
        cd ~
        git clone -b master --depth 1 https://invent.kde.org/documentation/docs-krita-org.git docs
    - name: Place new zh_TW PO catalogs
      run: |
        rsync -vr -f '+ *.po' -f '+ **/' -f '- *'  --prune-empty-dirs --del ./ ~/docs/locale/zh_TW/LC_MESSAGES/
    - name: Build HTML docs
      run: |
        cd ~/docs
        make html
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: html
        path: ~/docs/_build/html/
    - name: Deploy
      run: |
        git fetch --depth=1 origin gh-pages
        git worktree add _deploy gh-pages
        cd _deploy
        git config --local user.name github-actions[bot]
        git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
        git rm -rf *
        rsync -vr ~/docs/_build/html/ ./
        git add -A
        git commit -m "Action \`build\`: Deploy build of ${GITHUB_SHA::7}"
        git push
