name: Update POT

on:
  workflow_dispatch:

jobs:
  build_pot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Sphinx
      run: |
        python3 -m pip install git+https://github.com/alvinhochun/sphinx.git@gettext-no-subst-defs
    - name: Clone docs
      run: |
        cd ~
        git clone -b master --depth 1 https://invent.kde.org/documentation/docs-krita-org.git docs
    - name: Build POT templates
      run: |
        cd ~/docs
        patch -p1 < "${{ github.workspace }}/exclude_image_target.patch"
        make gettext
    - name: Update modified POT templates
      run: |
        bash sync_changed_pot.sh ~/docs/_build/gettext/ ./templates/
        git config --local user.name github-actions[bot]
        git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
        git checkout -b update-pot/$(date '+%Y%m%d-%H%M%S')
        git add -A
        if [[ -z $(git status -s) ]]; then
          echo "No changes to commit."
          exit
        fi
        git commit -m "action: Update POT templates"
    - name: Create new PO catalogs from POT templates
      run: |
        bash create_new_po_from_pot.sh ./templates/ ./locale/zh_TW/
        git add -A
        if [[ -z $(git status -s) ]]; then
          echo "No changes to commit."
          exit
        fi
        git commit -m "action: Create new PO catalogs"
    - name: Push changes
      run: |
        if [[ -z $(git diff-index "${{ github.sha }}" ) ]]; then
          echo "No changes to push."
          exit
        fi
        git push origin HEAD
